language: java

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - stage: build
      env: JDK=14
      script: source ./install-jdk.sh --feature 14

notifications:
  slack: zachaczcompany:z82lfise3i91VIZM8ghqN9Q0
    # on_success = change - default
    # of_failure = always - default

branches:
  only:
    - master

after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version