spring:
  h2:
    console:
      enabled: true
      path: /console

locationiq:
  rest-api:
    region: eu1
    format: json
    url: https://${locationiq.rest-api.region}.locationiq.com/v1/
    key: c6e6dd0380d596