spring:
  h2:
    console:
      enabled: true
      path: /console
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: "shopfinderappemailsender@gmail.com"
    password: "!Password123"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14

locationiq:
  rest-api:
    region: eu1
    format: json
    url: https://${locationiq.rest-api.region}.locationiq.com/v1/
    key: c6e6dd0380d596
    numberOfRequests: 2
    toleranceRatio: 2.0